name: studydeploy-api
location: southeastasia
type: Microsoft.App/containerApps
properties:
  managedEnvironmentId: /subscriptions/d34c4cea-a009-4676-82b1-b8263d155382/resourceGroups/AZ-LRN-ACA-RG/providers/Microsoft.App/managedEnvironments/az-lrn-studydeploy-env
  configuration:
    ingress:
      external: true
      targetPort: 8080
      transport: auto
    secrets:
      - name: demo-secret
        value: REPLACE_WITH_REAL_SECRET
  template:
    containers:
      - name: studydeploy-api
        image: ghcr.io/pierce23john/studydeploy-api:latest
        env:
          - name: DEPLOYMENT_TARGET
            value: aca
          - name: APP_MESSAGE
            value: Hello from ACA
          - name: DEMO_SECRET
            secretRef: demo-secret
        resources:
          cpu: 0.5
          memory: 1Gi
    scale:
      minReplicas: 0
      maxReplicas: 5
      rules:
        - name: http-scaling
          http:
            metadata:
              concurrentRequests: "20"
